<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
	/* Title */
	'Title_Create' => 'Créer votre partie',
	'Title_Loby' => 'Liste des salons de parties',
	'Title_Join' => 'Rejoindre une partie',
	'Title_Loading' => 'Chargement...',
	'Title_Map' => 'Carte',
	'Title_Game_Mail' => 'Messagerie',
	'Title_Game_Chat' => 'Chat de la partie',
	'Title_Game_News' => 'Dernières actualités',
	'Title_Game_Stats' => 'Statistiques',
	'Title_Game_Diplomacy' => 'Portail diplomatique',
	'Title_Game_History' => 'Histoire de la partie',
	'Title_Fight_Details' => 'Détails du combat',
	'Title_Game_New_Mail'=> 'Envoyer un message',

	/* Tabs */
	'Tab_Game_Name' => 'Nom de la partie',
	'Tab_Owner_Name' => "Propriétaire",
	'Tab_Max_Player' => "Nombre de joueurs",
	'Tab_Create_Time' => "Date de creation",
	'Tab_Rejoin' => "Rejoindre",

	/* Text*/
	'Creation_Rules' => 'Veuillez completer le formulaire pour créer votre partie :',
	'Join_Rules' => 'Veuillez entrer le mot de passe de la partie :',
	'Chat_General' => 'Chat général',
	'Text_Second_{nb}' => 'il y a {nb} sec',
	'Text_Min_{nb}' => 'Il y a {nb} min',
	'Text_Hour_{nb}' => 'Il y a {nb} h',
	'Text_Yesterday' => 'Hier',
	'Text_Week' => 'Cette semaine',
	'Text_Date' => 'd/m/Y',
	'Text_Load_Title' => 'Avancement',
	'Txt_Map_Creation' => 'Création de la carte',
	'Txt_Region_Creation' => 'Création des régions',
	'Txt_Player_Creation' => 'Création des joueurs',
	'Txt_Land_Assignation' => 'Assignation des pays',
	'Txt_Finalization' => 'Finalisation',
	'Txt_Game_Owner_ID' => 'ID du propriétaire de la partie',
	'Txt_Game_Max_Player' => 'Nombre de joueurs maximum',
	'Txt_Game_Create_Time' => 'Date de création',
	'Txt_Game_Statut' => 'Statut de la partie',
	'Txt_Game_Map_ID' => 'Game Map ID',
	'Txt_Game_Mod_ID' => 'Game Mod ID',
	'Txt_Game_Turn_Time' => 'Game Turn Time',
	'Txt_Game_Difficulty_ID' => 'ID du niveau de difficulté',
	'Txt_Game_Won_User_ID' => 'ID du gagnant',
	'Txt_Game_Won_Time' => 'Meilleur temps',
	'Txt_Game_Pwd' => 'Mot de passe de la partie',
	'Txt_Game_Key' => 'Clé de la partie',
	'Txt_History_Defeated' => 'a vaincu',
	'Txt_History_Conquest' => "et s'est emparé de",
	'Txt_History_Lost' => 'a perdu contre',
	'Txt_History_In' => 'en',
	'Txt_Diplomacy_Status_War' => 'Guerre',
	'Txt_Diplomacy_Status_Tension' => 'Tension',
	'Txt_Diplomacy_Status_Peace' => 'Paix',
	'Txt_Diplomacy_Table_User' => 'Joueur',
	'Txt_Diplomacy_Table_Progress' => 'Progression',
	'Txt_Diplomacy_Table_Status' => 'Status',
	'Txt_Fight_Attacker' => 'Attaquant',
	'Txt_Fight_Defender' => 'Défenseur',
	'Txt_Mail_Re' => 'Re',
	'Txt_Mail_By_To_{user}_{time}_{date}' => 'Réponse au mail de {user} à {time} le {date}',
	'Txt_Mail_Subject' => 'Sujet',
	'Txt_Mail_To' => 'Destinataire',
	'Txt_Stats_Most_Attacked_Land_Title' => 'Pays les plus attaqués',
	'Txt_Stats_Most_Attacked_Land_Description_{nb}' => 'Top {nb}',
	'Txt_Stats_Win_Rate_Title' => 'Ratio victoires / défaites',
	'Txt_Stats_Win_Rate_Description' => 'Ratio victoires / défaites moyen',
	'Txt_Stats_Count_Occuped_Land_Player_Title' => 'Pays occupés',
	'Txt_Stats_Count_Occuped_Land_Player_Description' => 'Nombre de pays moyen',
	'Txt_Stats_Player_Long_Turn_Title' => 'Joueur avec les tours les plus longs',
	'Txt_Stats_Player_Long_Turn_Description' => 'Temps moyen des tours',
	'Txt_Stats_Player_Long_Turn_Warning' => 'Attention données inexactes en cas de reprise de partie',
	'Txt_Show_Started_Game' => 'Montrer les parties en cours',
	'Txt_Show_Ended_Game' => 'Montrer les parties terminées',

	/* Errors & success */
	'Error_Name_Already_Use' => 'Nom de partie déjà utilisé',
	'Error_Password_Incorrect' => 'Un mot de passe est nécessaire : mot de passe incorrect.',
	'Error_User_Already_In_Game' => 'Vous êtes déjà dans une autre partie !',
	'Error_Game_Full' => 'La partie est pleine.',
	'Error_Game_Cant_Join' => 'Impossible de rejoindre la partie.',
	'Error_Last_Game_Cant_Join' => 'Impossible de rejoindre la dernière partie.',
	'Error_Game_Not_Exist' => "La partie n'existe plus.",
	'Error_Start_Multiple_Color' => "La partie n'a pas pu démarrer : Plusieurs joueurs ont la même couleur.",
	'Error_Start_Not_Ready' => "La partie n'a pas pu démarrer : les joueurs ne sont pas prêts.",
	'Error_Start_Stop' => "La partie n'a pas pu démarrer.",
	'Error_Max_Player_Nb' => "Le nombre de joueur maximum est 10.",
	'Error_Not_Owner'	=> "Vous n'avez pas les droits nécessaires pour réaliser cette opération.",
	'Success_User_Left_Game' => 'Vous avez quitté la partie.',
	'Success_User_Enter_Game_{params}' => 'Vous avez rejoint la partie : {params}.',
	'Success_Game_Created' => 'Partie créée.',
	'Success_Game_Join' => 'Partie rejointe.',
	'Notice_Game_Quit' => 'Partie quittée.',
	'Notice_Games_Quit' => 'Toutes les parties en cours sont désormais quittées.',
	'Notice_Last_Game_Entered' => 'Dernière partie rejointe',

	/* Buttons */
	'Button_Send' => 'Envoyer',
	'Button_Game_Create' => 'Créer une partie',
	'Button_Game_Enter' => 'Entrer dans la partie',
	'Button_Map_Enter' => 'Entrer dans la carte',
	'Button_Last_Game_Enter' => 'Retourner dans la dernière partie',
	'Button_Game_Return' => 'Retourner dans la partie',
	'Button_Game_Spec' => 'Regarder la partie',
	'Button_Game_Ban' => 'Vous avez été bannis',
	'Button_Game_End' => 'Partie terminée',
	'Button_Games_Quit' => 'Quitter toutes les parties en cours.',
	'Button_Enter_In_Game' => 'Entrer dans la partie',
	'Button_New_Mail' => 'Ecrire un mail',

	/* Form */
	'Form_Create_Name' => 'Nom de la partie',
	'Form_Create_Time' => 'Création',
	'Form_Create_Pwd' => 'Mot de passe',
	'Form_Create_Max_Player' => 'Nombre de joueurs',
	'Form_Create_Mod_Id' => 'Mode de jeu',
	'Form_Create_Difficulty_Id' => 'Difficulté',
	'Form_Create_Map_Id' => 'Carte',
	'Form_Create_Owner' => 'Hôte de la partie',
	'Form_Join_Pwd' => 'Mot de passe',
		
	// Info
	'Info_Game_Lobby_Antartic' => "Attention, vous avez 5% de chance d'être déplacé en Antarctique",
];
?>
